FROM tensorflow/tensorflow:2.3.1-gpu
RUN pip3 install -U pip
RUN apt-get update -qq && apt-get install -qq locales git
RUN echo 'en_US.UTF-8 UTF-8' >> /etc/locale.gen && locale-gen

ENV LANG=en_US.UTF-8

COPY . /mrcnn
RUN python3 -m pip install -r /mrcnn/requirements.txt
